# By default, NotRemoteRunner is used when RAILS_ENV == 'test'.
#
# You can pass options to memcached client by nesting the key value pairs
# under 'memcache_options'.
#
# You can also use a cluster of Starlings. Simply give a comma separated
# list of server:port, server:port, server:port values to listens_on.
#
production:
  listens_on: localhost:22122
  sleep_time: 30
  reset_time: 30
  memcache_options:
   compression: true
   debug: false
   namespace: maass
   readonly: false
   urlencode: false

development:
  listens_on: localhost:15151
  sleep_time: 30
  reset_time: 30
  memcache_options:
   compression: true
   debug: false
   namespace: risealumni
   readonly: false
   urlencode: false


test:
  listens_on: localhost:12345